<?php

namespace AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function addUser(DataUser $user)
    {
        $manager = $this->getEntityManager();
        $manager->persist($user);
        $manager->flush();
    }
    */


}
